In [ ]:
import os

os.chdir("D:\\ykim\\input/")
os.getcwd()

'D:\\ykim\\input'

In [2]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\.conda\envs\autodock\lib\site-packages (0.24.2)
Requirement already satisfied: scipy>=0.19.1 in c:\users\user\.conda\envs\autodock\lib\site-packages (from scikit-learn) (1.5.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\.conda\envs\autodock\lib\site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\user\.conda\envs\autodock\lib\site-packages (from scikit-learn) (1.1.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\user\.conda\envs\autodock\lib\site-packages (from scikit-learn) (1.19.5)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import numpy as np

In [4]:
from sklearn.cluster import KMeans
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import linkage, dendrogram
from sklearn.decomposition import PCA
import seaborn as sns

In [5]:
data = pd.read_csv("PAR_Kmeans_input.csv")
data

,Unnamed: 0,Name,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
0,1,A1AG1_DVNDEKNW_1_y2,0.021678,0.037153,0.050806,0.044764,0.079770,0.024358,0.053047,0.038489,...,0.029727,0.122356,0.027941,0.098174,0.036184,0.026136,0.091584,0.074380,0.001564,0.073009
1,2,A1AG1_DVNDEKNW_1_y6,0.004196,0.004029,0.002419,0.016787,0.237664,0.023700,0.156272,0.002179,...,0.368014,0.009819,0.013235,0.560122,0.009211,0.009334,1.076733,0.017800,0.035966,0.586283
2,3,A1AG1_DVNDEKNW_1_y7,0.002098,0.001343,0.041129,0.000799,0.092105,0.005925,0.043728,0.002179,...,0.079073,0.001511,0.000735,0.027397,0.023026,0.001245,0.096535,0.001271,0.016419,0.075221
3,4,A1AT_MIEQNTKSPL_1_y6,1.590210,1.275739,3.469355,4.363709,3.447368,8.144832,0.947670,2.366013,...,0.530916,1.839124,3.122059,1.256469,1.155263,4.614810,2.558581,1.753338,5.149335,2.256637
4,5,A1AT_MIEQNTKSPL_1_y7,1.042657,0.792301,3.650000,3.646683,3.371711,6.547729,0.833692,1.597676,...,0.302021,1.793051,2.255147,0.952816,1.059868,3.509023,2.287129,2.022250,4.105551,2.778761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,1872,VWF_RKTQCCDEY_1_y5,0.000000,0.000562,0.000000,0.000000,0.000000,0.003636,0.000000,0.000000,...,0.000561,0.000000,0.000586,0.001318,0.002661,0.000000,0.002288,0.000791,0.000808,0.000000
1872,1873,VWF_RKTQCCDEY_2_b8,0.001037,0.003375,0.001898,0.002863,0.001996,0.002424,0.004454,0.000841,...,0.000561,0.002330,0.001172,0.005270,0.005854,0.000000,0.016590,0.007120,0.005654,0.002346
1873,1874,VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,0.000000,0.000562,0.014231,0.000716,0.006986,0.001212,0.002970,0.002523,...,0.001684,0.000582,0.001757,0.001976,0.000000,0.000605,0.001716,0.003956,0.000808,0.003127
1874,1875,VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,0.002592,0.000000,0.020873,0.000716,0.001996,0.001818,0.002970,0.000841,...,0.001684,0.000582,0.001172,0.000000,0.000532,0.000605,0.002288,0.000791,0.003231,0.001564
1875,1876,VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,0.000000,0.001687,0.023719,0.003579,0.002994,0.001212,0.003712,0.001682,...,0.006738,0.006407,0.002929,0.000659,0.013305,0.018149,0.004005,0.002373,0.000000,0.000782

In [6]:
data.index = data['Name']

data

,Unnamed: 0,Name,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
Name,,,,,,,,,,,,,,,,,,,,,
A1AG1_DVNDEKNW_1_y2,1,A1AG1_DVNDEKNW_1_y2,0.021678,0.037153,0.050806,0.044764,0.079770,0.024358,0.053047,0.038489,...,0.029727,0.122356,0.027941,0.098174,0.036184,0.026136,0.091584,0.074380,0.001564,0.073009
A1AG1_DVNDEKNW_1_y6,2,A1AG1_DVNDEKNW_1_y6,0.004196,0.004029,0.002419,0.016787,0.237664,0.023700,0.156272,0.002179,...,0.368014,0.009819,0.013235,0.560122,0.009211,0.009334,1.076733,0.017800,0.035966,0.586283
A1AG1_DVNDEKNW_1_y7,3,A1AG1_DVNDEKNW_1_y7,0.002098,0.001343,0.041129,0.000799,0.092105,0.005925,0.043728,0.002179,...,0.079073,0.001511,0.000735,0.027397,0.023026,0.001245,0.096535,0.001271,0.016419,0.075221
A1AT_MIEQNTKSPL_1_y6,4,A1AT_MIEQNTKSPL_1_y6,1.590210,1.275739,3.469355,4.363709,3.447368,8.144832,0.947670,2.366013,...,0.530916,1.839124,3.122059,1.256469,1.155263,4.614810,2.558581,1.753338,5.149335,2.256637
A1AT_MIEQNTKSPL_1_y7,5,A1AT_MIEQNTKSPL_1_y7,1.042657,0.792301,3.650000,3.646683,3.371711,6.547729,0.833692,1.597676,...,0.302021,1.793051,2.255147,0.952816,1.059868,3.509023,2.287129,2.022250,4.105551,2.778761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VWF_RKTQCCDEY_1_y5,1872,VWF_RKTQCCDEY_1_y5,0.000000,0.000562,0.000000,0.000000,0.000000,0.003636,0.000000,0.000000,...,0.000561,0.000000,0.000586,0.001318,0.002661,0.000000,0.002288,0.000791,0.000808,0.000000
VWF_RKTQCCDEY_2_b8,1873,VWF_RKTQCCDEY_2_b8,0.001037,0.003375,0.001898,0.002863,0.001996,0.002424,0.004454,0.000841,...,0.000561,0.002330,0.001172,0.005270,0.005854,0.000000,0.016590,0.007120,0.005654,0.002346
VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,1874,VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,0.000000,0.000562,0.014231,0.000716,0.006986,0.001212,0.002970,0.002523,...,0.001684,0.000582,0.001757,0.001976,0.000000,0.000605,0.001716,0.003956,0.000808,0.003127
VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,1875,VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,0.002592,0.000000,0.020873,0.000716,0.001996,0.001818,0.002970,0.000841,...,0.001684,0.000582,0.001172,0.000000,0.000532,0.000605,0.002288,0.000791,0.003231,0.001564
VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,1876,VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,0.000000,0.001687,0.023719,0.003579,0.002994,0.001212,0.003712,0.001682,...,0.006738,0.006407,0.002929,0.000659,0.013305,0.018149,0.004005,0.002373,0.000000,0.000782

In [7]:
data = data.drop('Unnamed: 0', axis=1)
data = data.drop('Name', axis=1)

data

,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,30s-3,30s-4,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
Name,,,,,,,,,,,,,,,,,,,,,
A1AG1_DVNDEKNW_1_y2,0.021678,0.037153,0.050806,0.044764,0.079770,0.024358,0.053047,0.038489,0.010695,0.019315,...,0.029727,0.122356,0.027941,0.098174,0.036184,0.026136,0.091584,0.074380,0.001564,0.073009
A1AG1_DVNDEKNW_1_y6,0.004196,0.004029,0.002419,0.016787,0.237664,0.023700,0.156272,0.002179,0.349885,0.037752,...,0.368014,0.009819,0.013235,0.560122,0.009211,0.009334,1.076733,0.017800,0.035966,0.586283
A1AG1_DVNDEKNW_1_y7,0.002098,0.001343,0.041129,0.000799,0.092105,0.005925,0.043728,0.002179,0.058060,0.000878,...,0.079073,0.001511,0.000735,0.027397,0.023026,0.001245,0.096535,0.001271,0.016419,0.075221
A1AT_MIEQNTKSPL_1_y6,1.590210,1.275739,3.469355,4.363709,3.447368,8.144832,0.947670,2.366013,2.912911,7.787533,...,0.530916,1.839124,3.122059,1.256469,1.155263,4.614810,2.558581,1.753338,5.149335,2.256637
A1AT_MIEQNTKSPL_1_y7,1.042657,0.792301,3.650000,3.646683,3.371711,6.547729,0.833692,1.597676,2.631016,6.761194,...,0.302021,1.793051,2.255147,0.952816,1.059868,3.509023,2.287129,2.022250,4.105551,2.778761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VWF_RKTQCCDEY_1_y5,0.000000,0.000562,0.000000,0.000000,0.000000,0.003636,0.000000,0.000000,0.000599,0.000000,...,0.000561,0.000000,0.000586,0.001318,0.002661,0.000000,0.002288,0.000791,0.000808,0.000000
VWF_RKTQCCDEY_2_b8,0.001037,0.003375,0.001898,0.002863,0.001996,0.002424,0.004454,0.000841,0.001198,0.012177,...,0.000561,0.002330,0.001172,0.005270,0.005854,0.000000,0.016590,0.007120,0.005654,0.002346
VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,0.000000,0.000562,0.014231,0.000716,0.006986,0.001212,0.002970,0.002523,0.002994,0.001522,...,0.001684,0.000582,0.001757,0.001976,0.000000,0.000605,0.001716,0.003956,0.000808,0.003127
VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,0.002592,0.000000,0.020873,0.000716,0.001996,0.001818,0.002970,0.000841,0.000599,0.000761,...,0.001684,0.000582,0.001172,0.000000,0.000532,0.000605,0.002288,0.000791,0.003231,0.001564
VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,0.000000,0.001687,0.023719,0.003579,0.002994,0.001212,0.003712,0.001682,0.000599,0.001522,...,0.006738,0.006407,0.002929,0.000659,0.013305,0.018149,0.004005,0.002373,0.000000,0.000782

In [8]:
group_data = pd.read_csv("PAR_Kmeans_group.csv")
group_data.index = group_data['Name']
group_data = group_data.drop('Name', axis=1)
group_data

,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,30s-3,30s-4,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
Name,,,,,,,,,,,,,,,,,,,,,
group,20S,20S,20S,20S,20S,20S,30S,30S,30S,30S,...,40S,40S,40S,40S,50S,50S,50S,50S,50S,50S
A1AG1_DVNDEKNW_1_y2,0.021678322,0.037153089,0.050806452,0.044764189,0.079769737,0.02435813,0.053046595,0.03848947,0.010695187,0.019315189,...,0.029726516,0.122356495,0.027941176,0.098173516,0.036184211,0.026135657,0.091584158,0.074380165,0.001563722,0.07300885
A1AG1_DVNDEKNW_1_y6,0.004195804,0.004028648,0.002419355,0.016786571,0.237664474,0.023699803,0.156272401,0.002178649,0.349885409,0.037752414,...,0.368014269,0.009818731,0.013235294,0.560121766,0.009210526,0.009334163,1.076732673,0.017800381,0.035965598,0.586283186
A1AG1_DVNDEKNW_1_y7,0.002097902,0.001342883,0.041129032,0.000799361,0.092105263,0.005924951,0.043727599,0.002178649,0.058059587,0.000877963,...,0.079072533,0.001510574,0.000735294,0.02739726,0.023026316,0.001244555,0.096534653,0.001271456,0.016419077,0.075221239
A1AT_MIEQNTKSPL_1_y6,1.59020979,1.275738585,3.469354839,4.363709033,3.447368421,8.144832126,0.947670251,2.366013072,2.912910619,7.787532924,...,0.530915577,1.839123867,3.122058824,1.256468798,1.155263158,4.614810205,2.558580858,1.753337572,5.149335418,2.256637168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VWF_RKTQCCDEY_1_y5,0,0.00056243,0,0,0,0.003636364,0,0,0.000598802,0,...,0.000561482,0,0.000585823,0.001317523,0.00266099,0,0.00228833,0.000791139,0.000807754,0
VWF_RKTQCCDEY_2_b8,0.001036807,0.003374578,0.001897533,0.002863278,0.001996008,0.002424242,0.004454343,0.000841043,0.001197605,0.01217656,...,0.000561482,0.002329645,0.001171646,0.005270092,0.005854178,0,0.016590389,0.007120253,0.005654281,0.002345582
VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,0,0.00056243,0.014231499,0.00071582,0.006986028,0.001212121,0.002969562,0.002523129,0.002994012,0.00152207,...,0.001684447,0.000582411,0.001757469,0.001976285,0,0.000604961,0.001716247,0.003955696,0.000807754,0.003127443
VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,0.002592017,0,0.020872865,0.00071582,0.001996008,0.001818182,0.002969562,0.000841043,0.000598802,0.000761035,...,0.001684447,0.000582411,0.001171646,0,0.000532198,0.000604961,0.00228833,0.000791139,0.003231018,0.001563722
VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,0,0.001687289,0.023719165,0.003579098,0.002994012,0.001212121,0.003711952,0.001682086,0.000598802,0.00152207,...,0.006737788,0.006406523,0.002929115,0.000658762,0.013304949,0.01814882,0.004004577,0.002373418,0,0.000781861

In [9]:
group_info = group_data.loc['group']
group_info

20s-1    20S
20s-2    20S
20s-3    20S
20s-4    20S
20s-5    20S
20s-6    20S
30s-1    30S
30s-2    30S
30s-3    30S
30s-4    30S
30s-5    30S
30s-6    30S
40s-1    40S
40s-2    40S
40s-3    40S
40s-4    40S
40s-5    40S
40s-6    40S
50s-1    50S
50s-2    50S
50s-3    50S
50s-4    50S
50s-5    50S
50s-6    50S
Name: group, dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1876 entries, A1AG1_DVNDEKNW_1_y2 to VWF_VGNKGCSHPSVKCKKRVTIL_1_y8
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   20s-1   1876 non-null   float64
 1   20s-2   1876 non-null   float64
 2   20s-3   1876 non-null   float64
 3   20s-4   1876 non-null   float64
 4   20s-5   1876 non-null   float64
 5   20s-6   1876 non-null   float64
 6   30s-1   1876 non-null   float64
 7   30s-2   1876 non-null   float64
 8   30s-3   1876 non-null   float64
 9   30s-4   1876 non-null   float64
 10  30s-5   1876 non-null   float64
 11  30s-6   1876 non-null   float64
 12  40s-1   1876 non-null   float64
 13  40s-2   1876 non-null   float64
 14  40s-3   1876 non-null   float64
 15  40s-4   1876 non-null   float64
 16  40s-5   1876 non-null   float64
 17  40s-6   1876 non-null   float64
 18  50s-1   1876 non-null   float64
 19  50s-2   1876 non-null   float64
 20  50s-3   1876 non-null   float64
 21  50s-4   1876 non-null   float64
 22  50s-5   1876 non-null   float64
 23  50s-6   1876 non-null   float64
dtypes: float64(24)
memory usage: 366.4+ KB

In [11]:
data.describe(percentiles=[.25, .5, .75]).round(2)

,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,30s-3,30s-4,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
count,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,...,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00
mean,3.42,1.97,2.98,3.50,4.22,3.00,2.79,2.94,3.66,4.03,...,3.09,5.95,4.49,3.85,4.40,5.81,4.27,4.38,6.38,5.36
std,24.03,16.60,25.58,22.21,28.00,21.18,22.34,25.98,19.84,25.67,...,19.92,24.91,21.74,25.01,20.11,26.22,21.73,29.78,30.20,30.75
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.01,0.00,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.01,0.03,0.02,0.01,0.02,0.02,0.02,0.02,0.03,0.02
50%,0.17,0.09,0.12,0.19,0.23,0.15,0.17,0.21,0.27,0.30,...,0.24,0.60,0.39,0.31,0.51,0.65,0.39,0.32,0.82,0.36
75%,1.15,0.78,1.11,1.41,1.65,1.14,1.19,1.31,1.80,1.82,...,1.38,2.96,2.09,1.70,2.38,3.29,1.97,1.92,3.58,2.18
max,622.44,654.04,1024.34,821.73,1014.10,787.85,876.32,1022.49,679.07,925.69,...,745.97,681.46,560.09,920.66,595.40,602.10,627.10,1093.99,763.76,1031.70

In [ ]:
log_data_yh = np.log1p(data)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(log_data_yh)
scaled_data

array([[-0.62010809, -0.55301821, -0.5744583 , ..., -0.65481212,
        -0.85935908, -0.66744782],
       [-0.63964034, -0.59702769, -0.62906944, ..., -0.71044685,
        -0.82867389, -0.29541731],
       [-0.64200702, -0.60065942, -0.58517651, ..., -0.72728446,
        -0.84598134, -0.66548765],
       ...,
       [-0.64437867, -0.60171659, -0.61549847, ..., -0.72453127,
        -0.86004515, -0.73153672],
       [-0.64144916, -0.60247895, -0.60793745, ..., -0.72777789,
        -0.85784777, -0.73302137],
       [-0.64437867, -0.60019317, -0.60471206, ..., -0.7261533 ,
        -0.86077879, -0.73376457]])

In [14]:
import pandas as pd

scaled_df = pd.DataFrame(scaled_data, index=data.index, columns=data.columns)
scaled_df

,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,30s-3,30s-4,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
Name,,,,,,,,,,,,,,,,,,,,,
A1AG1_DVNDEKNW_1_y2,-0.620108,-0.553018,-0.574458,-0.620502,-0.614291,-0.610193,-0.597531,-0.640569,-0.707099,-0.700226,...,-0.666057,-0.703033,-0.730996,-0.618953,-0.752479,-0.809782,-0.668798,-0.654812,-0.859359,-0.667448
A1AG1_DVNDEKNW_1_y6,-0.639640,-0.597028,-0.629069,-0.649797,-0.473329,-0.610938,-0.485408,-0.683458,-0.401022,-0.681490,...,-0.343452,-0.798737,-0.745453,-0.245247,-0.778837,-0.825002,-0.013895,-0.710447,-0.828674,-0.295417
A1AG1_DVNDEKNW_1_y7,-0.642007,-0.600659,-0.585177,-0.666901,-0.602558,-0.631241,-0.608189,-0.683458,-0.658658,-0.719303,...,-0.612898,-0.806220,-0.757908,-0.689859,-0.765250,-0.832421,-0.664191,-0.727284,-0.845981,-0.665488
A1AT_MIEQNTKSPL_1_y6,0.432676,0.512442,1.102616,1.144970,0.847773,1.927202,0.139791,0.776524,0.724639,1.551233,...,-0.215682,0.137581,0.662377,0.147534,-0.020636,0.757144,0.534499,0.312953,0.789576,0.389115
A1AT_MIEQNTKSPL_1_y7,0.163919,0.188659,1.148518,0.990099,0.830051,1.704724,0.067488,0.464281,0.645557,1.421428,...,-0.399602,0.122762,0.425483,-0.006293,-0.065874,0.554939,0.453704,0.408784,0.620560,0.530628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VWF_RKTQCCDEY_1_y5,-0.644379,-0.601717,-0.631869,-0.667763,-0.693560,-0.633881,-0.659504,-0.686080,-0.717718,-0.720220,...,-0.698687,-0.807587,-0.758058,-0.717225,-0.785343,-0.833568,-0.755700,-0.727778,-0.860045,-0.734508
VWF_RKTQCCDEY_2_b8,-0.643206,-0.597911,-0.629673,-0.664677,-0.691500,-0.635281,-0.654176,-0.685067,-0.717085,-0.707571,...,-0.698687,-0.805479,-0.757470,-0.713032,-0.782166,-0.833568,-0.741273,-0.721295,-0.855656,-0.732279
VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,-0.644379,-0.601717,-0.615498,-0.666991,-0.686369,-0.636684,-0.655949,-0.683043,-0.715189,-0.718631,...,-0.697413,-0.807060,-0.756883,-0.716525,-0.787999,-0.833010,-0.756281,-0.724531,-0.860045,-0.731537
VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,-0.641449,-0.602479,-0.607937,-0.666991,-0.691500,-0.635982,-0.655949,-0.685067,-0.717718,-0.719425,...,-0.697413,-0.807060,-0.757470,-0.718627,-0.787467,-0.833010,-0.755700,-0.727778,-0.857848,-0.733021
VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,-0.644379,-0.600193,-0.604712,-0.663907,-0.690472,-0.636684,-0.655062,-0.684055,-0.717718,-0.718631,...,-0.691699,-0.801803,-0.755711,-0.717926,-0.774791,-0.816986,-0.753958,-0.726153,-0.860779,-0.733765

In [15]:
from sklearn.preprocessing import StandardScaler

log_data = np.log1p(data.to_numpy())
log_data

array([[0.02144669, 0.03647955, 0.04955792, ..., 0.0717439 , 0.0015625 ,
        0.07046671],
       [0.00418703, 0.00402055, 0.00241643, ..., 0.01764381, 0.03533394,
        0.46139366],
       [0.0020957 , 0.00134198, 0.04030573, ..., 0.00127065, 0.01628574,
        0.07252644],
       ...,
       [0.        , 0.00056227, 0.01413118, ..., 0.00394789, 0.00080743,
        0.00312256],
       [0.00258866, 0.        , 0.02065801, ..., 0.00079083, 0.00322581,
        0.0015625 ],
       [0.        , 0.00168587, 0.02344224, ..., 0.00237061, 0.        ,
        0.00078156]])

In [16]:
import scipy as sp, scipy.stats

In [ ]:
scaler = StandardScaler()
scaled_log_data = scaler.fit_transform(log_data.T).T

In [ ]:
scaler = StandardScaler()
scaled_log_data = scaler.fit_transform(log_data)

#plt.hist(scaled_log_data)
#plt.savefig("../output/histogram_log_z-score_data.png", dpi=300)

In [20]:
data_zlog = pd.DataFrame(scaled_log_data, index=data.index, columns=data.columns)
data_zlog

,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,30s-3,30s-4,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
Name,,,,,,,,,,,,,,,,,,,,,
A1AG1_DVNDEKNW_1_y2,-0.620108,-0.553018,-0.574458,-0.620502,-0.614291,-0.610193,-0.597531,-0.640569,-0.707099,-0.700226,...,-0.666057,-0.703033,-0.730996,-0.618953,-0.752479,-0.809782,-0.668798,-0.654812,-0.859359,-0.667448
A1AG1_DVNDEKNW_1_y6,-0.639640,-0.597028,-0.629069,-0.649797,-0.473329,-0.610938,-0.485408,-0.683458,-0.401022,-0.681490,...,-0.343452,-0.798737,-0.745453,-0.245247,-0.778837,-0.825002,-0.013895,-0.710447,-0.828674,-0.295417
A1AG1_DVNDEKNW_1_y7,-0.642007,-0.600659,-0.585177,-0.666901,-0.602558,-0.631241,-0.608189,-0.683458,-0.658658,-0.719303,...,-0.612898,-0.806220,-0.757908,-0.689859,-0.765250,-0.832421,-0.664191,-0.727284,-0.845981,-0.665488
A1AT_MIEQNTKSPL_1_y6,0.432676,0.512442,1.102616,1.144970,0.847773,1.927202,0.139791,0.776524,0.724639,1.551233,...,-0.215682,0.137581,0.662377,0.147534,-0.020636,0.757144,0.534499,0.312953,0.789576,0.389115
A1AT_MIEQNTKSPL_1_y7,0.163919,0.188659,1.148518,0.990099,0.830051,1.704724,0.067488,0.464281,0.645557,1.421428,...,-0.399602,0.122762,0.425483,-0.006293,-0.065874,0.554939,0.453704,0.408784,0.620560,0.530628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VWF_RKTQCCDEY_1_y5,-0.644379,-0.601717,-0.631869,-0.667763,-0.693560,-0.633881,-0.659504,-0.686080,-0.717718,-0.720220,...,-0.698687,-0.807587,-0.758058,-0.717225,-0.785343,-0.833568,-0.755700,-0.727778,-0.860045,-0.734508
VWF_RKTQCCDEY_2_b8,-0.643206,-0.597911,-0.629673,-0.664677,-0.691500,-0.635281,-0.654176,-0.685067,-0.717085,-0.707571,...,-0.698687,-0.805479,-0.757470,-0.713032,-0.782166,-0.833568,-0.741273,-0.721295,-0.855656,-0.732279
VWF_VGNKGCSHPSVKCKKRVTIL_1_b11,-0.644379,-0.601717,-0.615498,-0.666991,-0.686369,-0.636684,-0.655949,-0.683043,-0.715189,-0.718631,...,-0.697413,-0.807060,-0.756883,-0.716525,-0.787999,-0.833010,-0.756281,-0.724531,-0.860045,-0.731537
VWF_VGNKGCSHPSVKCKKRVTIL_1_y10,-0.641449,-0.602479,-0.607937,-0.666991,-0.691500,-0.635982,-0.655949,-0.685067,-0.717718,-0.719425,...,-0.697413,-0.807060,-0.757470,-0.718627,-0.787467,-0.833010,-0.755700,-0.727778,-0.857848,-0.733021
VWF_VGNKGCSHPSVKCKKRVTIL_1_y8,-0.644379,-0.600193,-0.604712,-0.663907,-0.690472,-0.636684,-0.655062,-0.684055,-0.717718,-0.718631,...,-0.691699,-0.801803,-0.755711,-0.717926,-0.774791,-0.816986,-0.753958,-0.726153,-0.860779,-0.733765

In [21]:
data_zlog.describe(percentiles=[.25, .5, .75]).round(2)

,20s-1,20s-2,20s-3,20s-4,20s-5,20s-6,30s-1,30s-2,30s-3,30s-4,...,40s-3,40s-4,40s-5,40s-6,50s-1,50s-2,50s-3,50s-4,50s-5,50s-6
count,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,...,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00,1876.00
mean,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,-0.00,-0.00,...,-0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,-0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-0.64,-0.60,-0.63,-0.67,-0.69,-0.64,-0.66,-0.69,-0.72,-0.72,...,-0.70,-0.81,-0.76,-0.72,-0.79,-0.83,-0.76,-0.73,-0.86,-0.73
25%,-0.63,-0.60,-0.62,-0.66,-0.68,-0.63,-0.65,-0.67,-0.70,-0.71,...,-0.69,-0.78,-0.74,-0.70,-0.77,-0.81,-0.74,-0.71,-0.83,-0.72
50%,-0.46,-0.49,-0.50,-0.48,-0.48,-0.47,-0.47,-0.46,-0.46,-0.44,...,-0.45,-0.38,-0.43,-0.43,-0.38,-0.37,-0.42,-0.44,-0.32,-0.44
75%,0.22,0.18,0.23,0.28,0.31,0.24,0.28,0.32,0.37,0.36,...,0.29,0.44,0.37,0.34,0.43,0.51,0.35,0.37,0.52,0.37
max,6.64,8.19,7.40,6.58,6.46,7.09,7.47,7.67,6.18,6.42,...,6.81,5.10,5.59,6.55,5.60,5.07,5.80,6.47,5.17,5.87

In [ ]:
data_zlog.to_csv("./Aging_PAR_log_norm_data.csv")

In [ ]:
data_log = pd.DataFrame(log_data, index=data.index, columns=data.columns)
data_log.to_csv("./Aging_PAR_log_data.csv")